events {}

http {
    upstream users {  server users-service:3001; }
    upstream products { server products-service:3002; }
    upstream orders { server orders-service:3003; }

    server {
        listen 80;

        location /api/users {
            proxy_pass https://users-service-production-5f85.up.railway.app;
        }

        location /api/products {
            proxy_pass https://product-service-production-00cf.up.railway.app;
        }

        location /api/orders {
            proxy_pass https://orders-service-production-1056.up.railway.app;
        }

        location / {
            return 200 '{"services": ["/api/users", "/api/products", "/api/orders"]}';
            add_header Content-Type application/json;
        }
    }
}