events {
    worker_connections 1024;
}

http {
    resolver 8.8.8.8;

    server {
        listen 80;

        # Для користувачів
        location /api/users {
            rewrite ^/api/(.*) /$1 break;
            proxy_pass https://users-service-production-5f85.up.railway.app;
            proxy_ssl_server_name on;
        }

        # Для продуктів
        location /api/products {
            rewrite ^/api/(.*) /$1 break;
            proxy_pass https://product-service-production-00cf.up.railway.app;
            proxy_ssl_server_name on;
        }

        # Для замовлень
        location /api/orders {
            rewrite ^/api/(.*) /$1 break;
            proxy_pass https://orders-service-production-1056.up.railway.app;
            proxy_ssl_server_name on;
        }

        # Головна сторінка шлюзу
        location / {
            return 200 '{"status": "Gateway is running", "message": "Use /api/users, /api/products, or /api/orders"}';
            add_header Content-Type application/json;
        }
    }
}