events {}

http {
    upstream users {  server users-service:3001; }
    upstream products { server products-service:3002; }
    upstream orders { server orders-service:3003; }

    server {
        listen 80;

        location /api/users {
            proxy_pass http://users-service-production.railway.internal:3001;
        }

        location /api/products {
            proxy_pass http://products-service-production.railway.internal:3002;
        }

        location /api/orders {
            proxy_pass http://orders-service-production.railway.internal:3003;
        }

        location / {
            return 200 '{"services": ["/api/users", "/api/products", "/api/orders"]}';
            add_header Content-Type application/json;
        }
    }
}