name: Deploy to Railway

on:
  push:
    branches:
      - main  #  або master, залежно від твоєї гілки

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Shortcut
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up --detach --project 9b5237fc-5b57-4579-b4e5-6e7f1ef4a82b --environment production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}